services:
  sas-qr:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/tna76874/sas_db:latest
    container_name: sas_qr_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
